export const STORAGE_KEYS = {
  CONTAINERS: "containers",
  RULES: "rules",
  PREFERENCES: "preferences",
  BOOKMARKS: "bookmarks", // Legacy bookmark associations
  BOOKMARK_METADATA: "bookmarkMetadata", // Our metadata layer on Firefox bookmarks
  BOOKMARK_TAGS: "bookmarkTags",
  FOLDER_METADATA: "folderMetadata", // Folder-level settings
  SYNC_STATE: "syncState",
  CACHE: "cache",
  CATEGORIES: "categories",
  STATS: "stats",
  TEMPLATES: "templates",
  DAILY_STATS: "dailyStats",
  GLOBAL_STATS: "globalStats",
  ACTIVE_SESSIONS: "activeSessions",
  RECENT_ACTIVITY: "recentActivity",
} as const

export const DEFAULT_PREFERENCES = {
  theme: "auto" as const,
  keepOldTabs: false,
  matchDomainOnly: true,
  syncEnabled: false,
  syncOptions: {
    syncRules: true,
    syncContainers: true,
    syncPreferences: true,
  },
  notifications: {
    showOnRuleMatch: false,
    showOnRestrict: true,
    showOnExclude: false,
  },
  advanced: {
    debugMode: false,
    performanceMode: false,
    cacheTimeout: 60000, // 1 minute
  },
  stats: {
    enabled: true,
    retentionDays: 30,
  },
}

export const MESSAGE_TYPES = {
  // Container operations
  GET_CONTAINERS: "GET_CONTAINERS",
  CREATE_CONTAINER: "CREATE_CONTAINER",
  UPDATE_CONTAINER: "UPDATE_CONTAINER",
  DELETE_CONTAINER: "DELETE_CONTAINER",
  SYNC_CONTAINERS: "SYNC_CONTAINERS",
  CLEAR_CONTAINER_COOKIES: "CLEAR_CONTAINER_COOKIES",
  OPEN_IN_CONTAINER: "OPEN_IN_CONTAINER",

  // Rule operations
  GET_RULES: "GET_RULES",
  CREATE_RULE: "CREATE_RULE",
  UPDATE_RULE: "UPDATE_RULE",
  DELETE_RULE: "DELETE_RULE",
  EVALUATE_URL: "EVALUATE_URL",
  TEST_PATTERN: "TEST_PATTERN",

  // Storage operations
  GET_PREFERENCES: "GET_PREFERENCES",
  UPDATE_PREFERENCES: "UPDATE_PREFERENCES",
  BACKUP_DATA: "BACKUP_DATA",
  RESTORE_DATA: "RESTORE_DATA",

  // Sync operations
  SYNC_PUSH: "SYNC_PUSH",
  SYNC_PULL: "SYNC_PULL",
  GET_SYNC_STATE: "GET_SYNC_STATE",

  // Logging
  LOG: "LOG",

  // Bookmarks
  GET_BOOKMARK_ASSOCIATIONS: "GET_BOOKMARK_ASSOCIATIONS",
  ADD_BOOKMARK_ASSOCIATION: "ADD_BOOKMARK_ASSOCIATION",
  REMOVE_BOOKMARK_ASSOCIATION: "REMOVE_BOOKMARK_ASSOCIATION",
  PROCESS_BOOKMARK_URL: "PROCESS_BOOKMARK_URL",

  // Bookmark Operations
  GET_BOOKMARKS: "GET_BOOKMARKS",
  CREATE_BOOKMARK: "CREATE_BOOKMARK",
  UPDATE_BOOKMARK: "UPDATE_BOOKMARK",
  DELETE_BOOKMARK: "DELETE_BOOKMARK",
  UPDATE_BOOKMARK_NATIVE: "UPDATE_BOOKMARK_NATIVE",
  DELETE_BOOKMARK_NATIVE: "DELETE_BOOKMARK_NATIVE",
  BULK_UPDATE_BOOKMARKS: "BULK_UPDATE_BOOKMARKS",
  BULK_DELETE_BOOKMARKS: "BULK_DELETE_BOOKMARKS",
  REORDER_BOOKMARKS: "REORDER_BOOKMARKS",
  MOVE_BOOKMARK: "MOVE_BOOKMARK",

  // Bookmark Tags
  GET_BOOKMARK_TAGS: "GET_BOOKMARK_TAGS",
  GET_TAG_CAPABILITIES: "GET_TAG_CAPABILITIES",
  CREATE_BOOKMARK_TAG: "CREATE_BOOKMARK_TAG",
  UPDATE_BOOKMARK_TAG: "UPDATE_BOOKMARK_TAG",
  DELETE_BOOKMARK_TAG: "DELETE_BOOKMARK_TAG",

  // Bookmark Folders
  GET_BOOKMARK_FOLDERS: "GET_BOOKMARK_FOLDERS",
  CREATE_BOOKMARK_FOLDER: "CREATE_BOOKMARK_FOLDER",
  UPDATE_BOOKMARK_FOLDER: "UPDATE_BOOKMARK_FOLDER",
  DELETE_BOOKMARK_FOLDER: "DELETE_BOOKMARK_FOLDER",
  DELETE_BOOKMARK_FOLDERS: "DELETE_BOOKMARK_FOLDERS",

  // Bookmark Bulk Actions
  BULK_ASSIGN_TAG: "BULK_ASSIGN_TAG",
  BULK_REMOVE_TAG: "BULK_REMOVE_TAG",
  BULK_ASSIGN_CONTAINER: "BULK_ASSIGN_CONTAINER",
  BULK_REMOVE_CONTAINER: "BULK_REMOVE_CONTAINER",
  BULK_OPEN_IN_CONTAINER: "BULK_OPEN_IN_CONTAINER",

  // Bookmark Import/Export
  EXPORT_BOOKMARKS_CSV: "EXPORT_BOOKMARKS_CSV",
  IMPORT_BOOKMARKS_CSV: "IMPORT_BOOKMARKS_CSV",

  // Bookmark Utils
  CHECK_BOOKMARK_RULE_MATCH: "CHECK_BOOKMARK_RULE_MATCH",
  MIGRATE_BOOKMARKS: "MIGRATE_BOOKMARKS",

  // Categories
  GET_CATEGORIES: "GET_CATEGORIES",
  ADD_CATEGORY: "ADD_CATEGORY",
  RENAME_CATEGORY: "RENAME_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  // Stats
  GET_STATS: "GET_STATS",
  RESET_STATS: "RESET_STATS",
  GET_GLOBAL_STATS: "GET_GLOBAL_STATS",
  GET_DAILY_STATS: "GET_DAILY_STATS",
  GET_ACTIVE_TABS: "GET_ACTIVE_TABS",
  GET_RECENT_ACTIVITY: "GET_RECENT_ACTIVITY",
  GET_CONTAINER_TRENDS: "GET_CONTAINER_TRENDS",
  RECORD_STAT_EVENT: "RECORD_STAT_EVENT",

  // Templates
  GET_TEMPLATES: "GET_TEMPLATES",
  APPLY_TEMPLATE: "APPLY_TEMPLATE",
  SAVE_TEMPLATE: "SAVE_TEMPLATE",
  DELETE_TEMPLATE: "DELETE_TEMPLATE",
  EXPORT_CONTAINER: "EXPORT_CONTAINER",
  IMPORT_CONTAINER: "IMPORT_CONTAINER",

  // Rules Import/Export
  EXPORT_RULES: "EXPORT_RULES",
  IMPORT_RULES: "IMPORT_RULES",

  // Template Generation
  GENERATE_TEMPLATE: "GENERATE_TEMPLATE",

  // Container Import/Export
  EXPORT_CONTAINERS: "EXPORT_CONTAINERS",
  IMPORT_CONTAINERS: "IMPORT_CONTAINERS",

  // Tag Import/Export
  EXPORT_TAGS: "EXPORT_TAGS",
  IMPORT_TAGS: "IMPORT_TAGS",

  // Bookmark Import/Export (Silo Format)
  EXPORT_BOOKMARKS_SILO: "EXPORT_BOOKMARKS_SILO",
  IMPORT_BOOKMARKS_SILO: "IMPORT_BOOKMARKS_SILO",

  // Bookmark Import/Export (Cross-Browser Format)
  EXPORT_BOOKMARKS_STANDARD: "EXPORT_BOOKMARKS_STANDARD",
  IMPORT_BOOKMARKS_STANDARD: "IMPORT_BOOKMARKS_STANDARD",
} as const

export const DEFAULT_CONTAINER_ICONS = [
  "fingerprint",
  "briefcase",
  "dollar",
  "cart",
  "fence",
  "fruit",
  "gift",
  "vacation",
  "tree",
  "chill",
] as const

export const DEFAULT_CONTAINER_COLORS = [
  "blue",
  "turquoise",
  "green",
  "yellow",
  "orange",
  "red",
  "pink",
  "purple",
  "toolbar",
] as const
